#include <mosquitto.h>

#define RPC_REQUEST_PREFIX "_RPC/in"
#define RPC_REQUEST_PREFIX_LENGTH 7

#define RPC_RESPONSE_PREFIX "_RPC/out"
#define RPC_RESPONSE_PREFIX_LENGTH 8

#define RPC_SUBSCRIBE_PREFIX RPC_REQUEST_PREFIX "/+/+"

#define RPC_REQUEST_RESPONSE_OFFSET \
  RPC_RESPONSE_PREFIX_LENGTH - RPC_REQUEST_PREFIX_LENGTH

#define RPC_RESPONSE_TOPIC_LENGTH(message)\
    strlen(message->topic) + RPC_REQUEST_RESPONSE_OFFSET * sizeof(char)

#define RPC_RESPONSE_TOPIC(buf, message)\
  sprintf(buf, RPC_RESPONSE_PREFIX "%s", &(message->topic)[RPC_REQUEST_PREFIX_LENGTH])
